"""create user_book_annotations table

Revision ID: 0577859df913
Revises: 771983911a99
Create Date: 2025-09-10 15:23:18.213911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0577859df913'
down_revision: Union[str, Sequence[str], None] = '771983911a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_book_annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_book_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_book_id'], ['user_books.id'], name='fk_user_book_annotations_user_book_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_book_annotations_id'), 'user_book_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_user_book_annotations_user_book_id'), 'user_book_annotations', ['user_book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_book_annotations_user_book_id'), table_name='user_book_annotations')
    op.drop_index(op.f('ix_user_book_annotations_id'), table_name='user_book_annotations')
    op.drop_table('user_book_annotations')
    # ### end Alembic commands ###
