"""add publisher, authors and categories columns to books table

Revision ID: 22795a2bfdbf
Revises: 0577859df913
Create Date: 2025-09-15 14:43:45.187954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22795a2bfdbf'
down_revision: Union[str, Sequence[str], None] = '0577859df913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('books', sa.Column('authors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('books', sa.Column('categories', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'categories')
    op.drop_column('books', 'authors')
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###
