"""create user_books table

Revision ID: 771983911a99
Revises: 9d307622098c
Create Date: 2025-09-09 14:06:23.347386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771983911a99'
down_revision: Union[str, Sequence[str], None] = '9d307622098c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_books',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('reading_status', sa.String(length=50), nullable=True),
    sa.Column('rating_star', sa.SmallInteger(), nullable=True),
    sa.Column('reading_start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('reading_end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_user_books_book_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_books_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_books_book_id'), 'user_books', ['book_id'], unique=False)
    op.create_index(op.f('ix_user_books_id'), 'user_books', ['id'], unique=False)
    op.create_index(op.f('ix_user_books_user_id'), 'user_books', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_books_user_id'), table_name='user_books')
    op.drop_index(op.f('ix_user_books_id'), table_name='user_books')
    op.drop_index(op.f('ix_user_books_book_id'), table_name='user_books')
    op.drop_table('user_books')
    # ### end Alembic commands ###
